### ISSUE TITLE
Home assistant Integration not fully loaded

### ISSUE THREAD

**Issue by rikroe** [bimmerconnected/bimmer_connected#642]
Good morning,
I have a BMW 318d from 2018 and I just installed the BMW Connected Drive integration. after having entered my login and password, it found 6 entities. but the problem is that everything remains “unknown”.
Is there anything more I need to do after installing the integration? why doesn't this work?
thank you.

_Originally posted by @schumi2309 in https://github.com/bimmerconnected/bimmer_connected/discussions/641_

**Comment by rikroe** [comment]
That seems not normal.
Have you tried reloading the integration? 

Otherwise, please go to the integrations page, download a diagnostic report and upload it.

**Comment by schumi2309** [comment]
yes, I have already reloaded the integration, restarted Home Assistant, but that doesn't change anything.
here is the diagnosis concerning the bmw integration:

![Capture d’écran 2024-08-02 à 18 40 35](https://github.com/user-attachments/assets/783e1487-19cb-46fb-a0e8-c63ba26209ba)

**Comment by rikroe** [comment]
Could you please provide the whole file?
It is stripped of any personal information and safe to upload publicly.

**Comment by schumi2309** [comment]
[bmw_connected_drive-01J44D5S2PWNMV1HFER81WBJ9P-318d-00132b25657d372666c744150f4e90a1.json](https://github.com/user-attachments/files/16473372/bmw_connected_drive-01J44D5S2PWNMV1HFER81WBJ9P-318d-00132b25657d372666c744150f4e90a1.json)

**Comment by rikroe** [comment]
Thanks for providing this! However I've got some bad news - on pre-LCI F31 vehicles (i.e. with NBT) the only thing we can provide are `buttons` (for the remote services), `lock` (to lock/unlock, but without the current lock state) and `device_tracker` (if vehicle finder server was run).

The API does not provide more information, thats also why you dont have more options in the MyBMW app.

**Comment by schumi2309** [comment]
so if I understand you correctly, I have 6 entities but no status feedback, neither for the tracker, nor for the lock.
no information comes back. ?
so, what use are the 6 entities to me if in any case, nothing works and no state goes back to HA???
Is that what I should understand?

**Comment by rikroe** [comment]
Exactly. On your pre-facelift 3 series F31, you can only control the car but will not get any status information back.

This is a limitation of the BMW API and the same in the MyBMW app.

**Comment by schumi2309** [comment]
In my case, I don't even control my car in HA.
nothing works. I only have the entities but they are of no use. If I press a button I have:
Failed to call the service.
so I don't even know how to control it.
so, what is the point of integrating if I don't know how to control it or have the status??

**Comment by rikroe** [comment]
Is there any further log message when you call the service?

The point of this integration is that if you have a newer car (3 series after 2019) or some other newer model, you also have status.

Why BMW is not able to provide the status on their first generation connected vehicles, please ask BMW.

**Comment by schumi2309** [comment]
Here is the message when I press the service:
![Capture d’écran 2024-08-03 à 10 46 32](https://github.com/user-attachments/assets/dded53c1-5388-4cd2-8cbb-ddc6440489b4)

However, in the MyBMW app, I have access to all these commands, for example, it opens or closes my doors, and sends me a notification on my smartphone after execution.

![IMG_2736](https://github.com/user-attachments/assets/db189bff-ac9c-4fef-9392-048b0e41b289)

**Comment by rikroe** [comment]
You should be able to lock/unlock your car.

For vehicle finder it seems that the BMW API reports it is unavailable, but apparently it will work nevertheless:
![image](https://github.com/user-attachments/assets/78ffb063-d096-4b6d-8eea-63add029538a)

I'll put in a PR for this. However please keep in mind that you will have to call this service to get it updated, as the car will not update it by itself.
Calling the API too often will also result in rate limits by the API.

**Comment by schumi2309** [comment]
Thanks for your help.
But what is PR?
Could you tell me what I should do?
Thanks again...

**Comment by rikroe** [comment]
Pull request = the request to merge code, in this case #643. 
This needs to be merged into this code base first.

Then we need to create a new version release of this library and Create another PR with home assistant to have this included as well. Then you can get the latest update of HA and have the fixes.

It's a process, please have some patience.

**Comment by schumi2309** [comment]
yes, yes, of course, no worries.
I just wanted to know what to do and how to do it.
that's very kind of you, once again a big thank you...

**Comment by rybackisback** [comment]
I also get the error failed to perform action error. see attached. 
<img width="416" alt="Screenshot 2024-08-08 172325" src="https://github.com/user-attachments/assets/8948984d-9cc6-45a7-a38b-26f93020df24">

**Comment by rikroe** [comment]
> I just wanted to know what to do and how to do it. 

Just install the latest Home Assistant. Although be warned that the current issue is not yet integrated. 

@rybackisback please also provide a diagnostics json.

**Comment by schumi2309** [comment]
> > Je voulais juste savoir quoi faire et comment le faire.
> 
> Il suffit d'installer la dernière version de Home Assistant. Sachez toutefois que la version actuelle n'est pas encore intégrée.
> 
> @rybackisbackveuillez également fournir un json de diagnostic.

Do you have any news regarding my problem?
I just updated HA again, but nothing changes.
Thanks in advance...

**Comment by rikroe** [comment]
The changes got merged into HA Core repo, so will be available with HA 2025.9.

**Comment by schumi2309** [comment]
Ok, thanks.

But: HA 2025.9 or HA 2024.9 ?

**Comment by rikroe** [comment]
Sorry, 2024.9 😉

**Comment by schumi2309** [comment]
hello, it's me again.
I don't see anything new in version 2024.9
Do I need to re-install the BMW Connect integration?

**Comment by rikroe** [comment]
No worries!

You will not see any new sensors etc. as your car unfortunately does not support them. (Un)locking the car and using the services however should work now.

**Comment by schumi2309** [comment]
unfortunately, it still doesn't work, even since the update!
here are the captures:

![Capture d’écran 2024-09-13 à 17 22 24](https://github.com/user-attachments/assets/b3512cb8-f154-4f73-9774-ead4d25595a5)

![Capture d’écran 2024-09-13 à 17 22 14](https://github.com/user-attachments/assets/5eb6e2ab-3dd7-4a40-8086-1de454b774d6)

I would really have hoped to at least get the status back on my sensors, but nothing!
Thank you.

**Comment by schumi2309** [comment]
No info for my problem? 
it still doesn't work.

**Comment by rikroe** [comment]
You need to buy a new car to get sensors.

Your car does not support it, you will never see sensors.
